/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6 for MT6752. Copyright MediaTek Inc. (C) 2013.
 * Mon Sep 29 21:32:28 2014
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H


#define AUXADC_TEMPERATURE_CHANNEL     0
#define AUXADC_TEMPERATURE1_CHANNEL     1


#endif //_CUST_AUXADC_TOOL_H


