/*
 * Generated by MTK SP DrvGen Version 03.13.6  for MT6752. Copyright MediaTek Inc. (C) 2013.
 * Mon Sep 29 21:32:28 2014
 * Do Not Modify the File.
 */

#define CUST_EINT_MD_LEVEL_SENSITIVE        0
#define CUST_EINT_MD_EDGE_SENSITIVE         1




#define PAD_INT_SIM1            0
#define PAD_INT_SIM2            1
#define PAD_I2S0_LRCK            2
#define PAD_SPI_CSB            5
#define PAD_SPI_MO            7


#define CUST_EINT_POLARITY_LOW              0
#define CUST_EINT_POLARITY_HIGH             1
#define CUST_EINT_EDGE_SENSITIVE            0
#define CUST_EINT_LEVEL_SENSITIVE           1




#define CUST_EINT_MD1_CNT      0


