/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6  for MT6580. Copyright MediaTek Inc. (C) 2013.
 * Wed May 10 15:14:15 2017
 * Do Not Modify the File.
 */





#define PMIC_APP_PROXIMITY_SENSOR_VDD         "VGP1"

#define PMIC_APP_CAP_TOUCH_VDD         "VGP2"

#define PMIC_APP_MAIN_CAMERA_POWER_AF         "VCAMAF"

#define PMIC_APP_MAIN_CAMERA_POWER_D         "VCAMD"

#define PMIC_APP_SUB_CAMERA_POWER_D         "VCAMD"

#define PMIC_APP_MAIN_CAMERA_POWER_IO         "VCAMIO"

#define PMIC_APP_SUB_CAMERA_POWER_IO         "VCAMIO"

#define PMIC_APP_MAIN_CAMERA_POWER_A         "VCAMA"

#define PMIC_APP_SUB_CAMERA_POWER_A         "VCAMA"




/**********Output default name********************/

#define PMIC_APP_CAP_TOUCH_VIO         ""

#define PMIC_APP_MHL_POWER_LDO1         ""

#define PMIC_APP_MHL_POWER_LDO2         ""

#define PMIC_APP_SUB_CAMERA_POWER_AF         ""

#define PMIC_APP_ACCELEROMETER_SENSOR_VDD         ""

#define PMIC_APP_ACCELEROMETER_SENSOR_VIO         ""

#define PMIC_APP_AMBIENT_LIGHT_SENSOR_VDD         ""

#define PMIC_APP_AMBIENT_LIGHT_SENSOR_VIO         ""

#define PMIC_APP_PROXIMITY_SENSOR_VIO         ""

#define PMIC_APP_MAGNETOMETER_SENSOR_VDD         ""

#define PMIC_APP_MAGNETOMETER_SENSOR_VIO         ""

#define PMIC_APP_GYROSCOPE_VDD         ""

#define PMIC_APP_GYROSCOPE_VIO         ""

#define PMIC_APP_BAROMETER_VDD         ""

#define PMIC_APP_BAROMETER_VIO         ""

#define PMIC_APP_MEMORY_CARD_VDD         ""





